version: '3'

services:
  coder:
    build:
      context: ./
      dockerfile: ./.docker/coder/Dockerfile
    container_name: drupal_coder
    volumes:
      - "sharedvolume:/home/coder/project/code-server"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8443:8443"
    env_file:
      - "./.docker/.env"
  apache:
    container_name: drupal_apache
    build:
      context: ./
      dockerfile: ./.docker/apache/Dockerfile
    volumes:
      - "sharedvolume:/home/coder/project/code-server"
    ports:
      - "8080:8080"
    env_file:
      - "./.docker/.env"
  mariadb:
    build:
      context: ./
      dockerfile: ./.docker/mariadb/Dockerfile
    container_name: drupal_mariadb
    volumes:
      - "mariadbvolume:/var/lib/mysql"
    env_file:
      - "./.docker/.env"

volumes:
  sharedvolume:
  mariadbvolume: